from ubuntu:16.04

# Install SSH server and Git
RUN apt-get update && \
    apt-get install -y openssh-server git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/run/sshd

# Get Docker Engine binaries
#RUN wget https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz && \
#    tar -xf docker-latest.tgz && \
#    mv docker/docker /bin/ && \
#    rm -rf docker-latest.tgz docker

# Install Docker Remote API client for Python
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    pip install docker-py
    
# Copy SSH Jenkins credentials
COPY jenkins_id_rsa.pub /root/.ssh/authorized_keys
COPY docker-run.py /usr/local/bin/

EXPOSE 22
VOLUME /var/run/docker.sock

CMD ["/usr/sbin/sshd", "-D"]
