IF(NOT DEFINED EIGEN_INSTALL_DIR)
    SET(EIGEN_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/eigen")
ENDIF()

EXTERNALPROJECT_ADD(
    EIGEN
#    URL                http://bitbucket.org/eigen/eigen/get/3.2.2.tar.bz2
    URL                ${EIGEN_ARCHIVE}
    DOWNLOAD_DIR       ${EIGEN_SOURCE_DIR}
    SOURCE_DIR         ${EIGEN_SOURCE_DIR}
    INSTALL_DIR        ${EIGEN_INSTALL_DIR}
    CMAKE_ARGS         -D CMAKE_INSTALL_PREFIX=${EIGEN_INSTALL_DIR}
                       -D EIGEN_BUILD_PKGCONFIG:BOOL=ON
    BUILD_IN_SOURCE    0
)

FILE(APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(EIGEN_INSTALL_DIR \"${EIGEN_INSTALL_DIR}\")\n")
