FUNCTION(ADD_CAP_TEST TEST_NAME)
    ADD_EXECUTABLE(${TEST_NAME}.exe ${PROJECT_SOURCE_DIR}/test/${TEST_NAME}.cc)
    TARGET_LINK_LIBRARIES(${TEST_NAME}.exe cap)
    TARGET_LINK_LIBRARIES(${TEST_NAME}.exe ${Boost_LIBRARIES})
    IF(ENABLE_DEAL_II)
        TARGET_LINK_LIBRARIES(${TEST_NAME}.exe deal_II)
    ENDIF()
    IF(ENABLE_GSL)
        TARGET_LINK_LIBRARIES(${TEST_NAME}.exe ${GSL_LIBRARIES})
    ENDIF()
    IF(ENABLE_TASMANIAN)
        TARGET_LINK_LIBRARIES(${TEST_NAME}.exe ${TASMANIAN_LIBRARIES})
    ENDIF()
    ADD_TEST(${TEST_NAME} ${TEST_NAME}.exe)
ENDFUNCTION()

FUNCTION(COPY_CAP_INPUT_FILE INPUT_FILE)
    ADD_CUSTOM_COMMAND(
        OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${INPUT_FILE}
        DEPENDS ${PROJECT_SOURCE_DIR}/test/data/${INPUT_FILE}
        COMMAND ${CMAKE_COMMAND}
        ARGS -E copy ${PROJECT_SOURCE_DIR}/test/data/${INPUT_FILE} ${CMAKE_CURRENT_BINARY_DIR}/${INPUT_FILE}
        COMMENT "Copying ${INPUT_FILE}"
    )
    ADD_CUSTOM_TARGET(
       ${INPUT_FILE} ALL
       DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/${INPUT_FILE}
    )
ENDFUNCTION()
