IF(NOT DEFINED NOWPAC_INSTALL_DIR)
    SET(NOWPAC_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/nowpac")
ENDIF()

EXTERNALPROJECT_ADD(
    NOWPAC
    GIT_REPOSITORY     git@bitbucket.org:fmaugust/nowpac.git
    GIT_TAG            NOWPACv1.0
    DOWNLOAD_DIR       ${NOWPAC_SOURCE_DIR}
    SOURCE_DIR         ${NOWPAC_SOURCE_DIR}
    INSTALL_DIR        ${NOWPAC_INSTALL_DIR} 
    CMAKE_ARGS         -D CMAKE_INSTALL_PREFIX=${NOWPAC_INSTALL_DIR}
                       -D EIGEN_INSTALL_DIR=${EIGEN_INSTALL_DIR}
                       -D NLOPT_INSTALL_DIR=${NLOPT_INSTALL_DIR}
    BUILD_IN_SOURCE    0
    DEPENDS            NLOPT EIGEN
)

FILE(APPEND "${CMAKE_INSTALL_PREFIX}/TPLs.cmake" "SET(NOWPAC_INSTALL_DIR \"${NOWPAC_INSTALL_DIR}\")\n")
