FIND_LIBRARY(GSL_LIBRARIES
    NAMES gsl
    PATHS ${GSL_INSTALL_DIR}/lib
    NO_DEFAULT_PATH
    )
FIND_PATH(GSL_INCLUDE_DIR gsl/gsl_version.h
    PATHS ${GSL_INSTALL_DIR}/include
    NO_DEFAULT_PATH
    )
MESSAGE("GSL_LIBRARIES=${GSL_LIBRARIES}")
MESSAGE("GSL_INCLUDE_DIR=${GSL_INCLUDE_DIR}")
INCLUDE_DIRECTORIES(SYSTEM ${GSL_INCLUDE_DIR})
