FIND_LIBRARY(TASMANIAN_LIBRARIES
    NAMES tasmaniansparsegrid
    PATHS ${TASMANIAN_INSTALL_DIR}/lib
    NO_DEFAULT_PATH
    )
FIND_PATH(TASMANIAN_INCLUDE_DIR tasmanian/TasmanianSparseGrid.hpp
    PATHS ${TASMANIAN_INSTALL_DIR}/include
    NO_DEFAULT_PATH
    )
MESSAGE("TASMANIAN_LIBRARIES=${TASMANIAN_LIBRARIES}")
MESSAGE("TASMANIAN_INCLUDE_DIR=${TASMANIAN_INCLUDE_DIR}")
INCLUDE_DIRECTORIES(SYSTEM ${TASMANIAN_INCLUDE_DIR})
LINK_DIRECTORIES(${TASMANIAN_LIBRARY_DIR})
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
ADD_DEFINITIONS(-DWITH_TASMANIAN)
